//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanjyShops.Business_Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanjyShops.Business_Models.Resources.ModelResources", typeof(ModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid FSSAI number.
        /// </summary>
        internal static string ACC_Type {
            get {
                return ResourceManager.GetString("ACC_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Account Number.
        /// </summary>
        internal static string AccountNumber_Required {
            get {
                return ResourceManager.GetString("AccountNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Address.
        /// </summary>
        internal static string Address_Required {
            get {
                return ResourceManager.GetString("Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Bank Name.
        /// </summary>
        internal static string BankName_Required {
            get {
                return ResourceManager.GetString("BankName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Must Be Equall.
        /// </summary>
        internal static string ConfirmPassword_mismatch {
            get {
                return ResourceManager.GetString("ConfirmPassword_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm Password.
        /// </summary>
        internal static string ConfirmPassword_Required {
            get {
                return ResourceManager.GetString("ConfirmPassword_Required", resourceCulture);
            }
        }
        internal static string Country_Code_Required
        {
            get
            {
                return ResourceManager.GetString("Country_Code_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email .
        /// </summary>
        internal static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid E-Mail id.
        /// </summary>
        internal static string Email_Type {
            get {
                return ResourceManager.GetString("Email_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter FSSAI.
        /// </summary>
        internal static string FSSAI_Required {
            get {
                return ResourceManager.GetString("FSSAI_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid FSSAI number.
        /// </summary>
        internal static string FSSAI_Type {
            get {
                return ResourceManager.GetString("FSSAI_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload FSSAI .
        /// </summary>
        internal static string FSSAICard_Required {
            get {
                return ResourceManager.GetString("FSSAICard_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid GST number.
        /// </summary>
        internal static string GST_Type {
            get {
                return ResourceManager.GetString("GST_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter GST Number.
        /// </summary>
        internal static string GSTNumber_Required {
            get {
                return ResourceManager.GetString("GSTNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload ID Card.
        /// </summary>
        internal static string ID_Required {
            get {
                return ResourceManager.GetString("ID_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select ID Type.
        /// </summary>
        internal static string ID_Type_Required {
            get {
                return ResourceManager.GetString("ID_Type_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter IFSC Code.
        /// </summary>
        internal static string IFSCCode_Required {
            get {
                return ResourceManager.GetString("IFSCCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Owner Name.
        /// </summary>
        internal static string OwnerName_Required {
            get {
                return ResourceManager.GetString("OwnerName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload PAN Card.
        /// </summary>
        internal static string PAN_Required {
            get {
                return ResourceManager.GetString("PAN_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid FSSAI number.
        /// </summary>
        internal static string PAN_Type {
            get {
                return ResourceManager.GetString("PAN_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter PAN Number .
        /// </summary>
        internal static string PANNumber_Required {
            get {
                return ResourceManager.GetString("PANNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Passbook or Bank Statement.
        /// </summary>
        internal static string Passbook_Required {
            get {
                return ResourceManager.GetString("Passbook_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        internal static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password contains 7 letters Upercase,Lowercase,Special character.
        /// </summary>
        internal static string Password_Type {
            get {
                return ResourceManager.GetString("Password_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Phone Number.
        /// </summary>
        internal static string PhoneNumber_Regular {
            get {
                return ResourceManager.GetString("PhoneNumber_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Phonenumber.
        /// </summary>
        internal static string Phonenumber_Required {
            get {
                return ResourceManager.GetString("Phonenumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Pincode.
        /// </summary>
        internal static string Pincode_Required {
            get {
                return ResourceManager.GetString("Pincode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Pincode.
        /// </summary>
        internal static string pincode_Type {
            get {
                return ResourceManager.GetString("pincode_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Shop Name.
        /// </summary>
        internal static string ShopName_Required {
            get {
                return ResourceManager.GetString("ShopName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Shop Type.
        /// </summary>
        internal static string ShopType_Required {
            get {
                return ResourceManager.GetString("ShopType_Required", resourceCulture);
            }
        }
    }
}
