//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanjyShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENT_DETAILS()
        {
            this.SANJY_SHOP_REGISTRATION = new HashSet<SANJY_SHOP_REGISTRATION>();
        }
    
        public long Agent_Id { get; set; }
        public string Agent_Name { get; set; }
        public string Country_Name { get; set; }
        public string State_Name { get; set; }
        public string City_Name { get; set; }
        public string Location_Name { get; set; }
        public string Agency_Name { get; set; }
        public string Licence_Number { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string Phonenumber { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANJY_SHOP_REGISTRATION> SANJY_SHOP_REGISTRATION { get; set; }
    }
}
