//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanjyShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_NAMES
    {
        public int Bank_Id { get; set; }
        public string Bank_Name { get; set; }
    }
}
