//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanjyShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANJY_SHOP_REGISTRATION
    {
        public long Shop_Id { get; set; }
        public Nullable<bool> Is_Refferal { get; set; }
        public Nullable<long> Agent_Id { get; set; }
        public string Shop_Name { get; set; }
        public string Owner_Name { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string GST_Number { get; set; }
        public string FSSAI_Number { get; set; }
        public string Address { get; set; }
        public string pincode { get; set; }
        public bool Is_Phone_Number_Verified { get; set; }
        public int Shop_Type_Id { get; set; }
        public string Bank_Account_Number { get; set; }
        public string IFSC_Code { get; set; }
        public string Bank_Name { get; set; }
        public string PAN_Number { get; set; }
        public string FSSAI { get; set; }
        public int Id_Proof_Type_Id { get; set; }
        public string Id_Proof_Front { get; set; }
        public string Id_Proof_Back { get; set; }
        public string PAN_Card { get; set; }
        public string Passbook_Bank_Statement { get; set; }
        public int Phone_Number_Country_Code_Id { get; set; }
    
        public virtual AGENT_DETAILS AGENT_DETAILS { get; set; }
        public virtual ID_PROOF_TYPES ID_PROOF_TYPES { get; set; }
        public virtual SHOP_TYPES SHOP_TYPES { get; set; }
        public virtual COUNTRY_CODES COUNTRY_CODES { get; set; }
    }
}
