//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanjyShop.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SanjyShopDatabase : DbContext
    {
        public SanjyShopDatabase()
            : base("name=SanjyShopDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENT_DETAILS> AGENT_DETAILS { get; set; }
        public virtual DbSet<BANK_NAMES> BANK_NAMES { get; set; }
        public virtual DbSet<ID_PROOF_TYPES> ID_PROOF_TYPES { get; set; }
        public virtual DbSet<SHOP_TYPES> SHOP_TYPES { get; set; }
        public virtual DbSet<SANJY_SHOP_REGISTRATION> SANJY_SHOP_REGISTRATION { get; set; }
        public virtual DbSet<COUNTRY_CODES> COUNTRY_CODES { get; set; }
    }
}
